beurs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import  routers
from api.account.viewsets import UserViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup-customer/',include('users.urls'))
    
]
# (temp) path for browser api view
urlpatterns +=[
    path('api-auth/', include('rest_framework.urls'))
    ]
# djoser path
urlpatterns +=[
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls')),
]
# other api paths
# urlpatterns +=[
#     path('api/v1/', include(router.urls)),
# ]

#djoser urls
# ************************************
# step N 1: register user

# url: auth/users/
# other features
# url: auth/users/...кучи разных экстра для создания и опереций над юзерами
# smth like: confirm email, reset psw
# step N2
# activate
# auth/users/activate
# http://127.0.0.1:8080/activate/NDM/5ir-d995..


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import CustReg

app_name = 'users'

urlpatterns = [
    path('',CustReg.as_view(),name="customer-signup")
]

users/models.py
#  https://djangotricks.blogspot.com/search/label/Django%20REST%20Framework (about upload drf)
import os
import sys
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from .utils import upload_to
import uuid


class User(AbstractUser):
    """ 
    username + email for signup; email for login;
    user should choose at the moment of signUp one of two options: 
    is_customer or is employee;
    admin/staff members could keep default values;
    """
    username = models.CharField(_("Username"),unique=True,max_length=120)
    email = models.EmailField(_("Email"),unique=True)
    avatar = models.ImageField(_("Avatar"), upload_to=upload_to, blank=True)
    phone_number = models.CharField(max_length=20,blank=True)
    is_customer = models.BooleanField(_("customer status"),default=False)
    is_employee = models.BooleanField(_("employee status"),default=False)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username

class Customer(models.Model):
    """ extra attr unid to display in public space"""
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    unid = models.UUIDField(max_length=255, default = uuid.uuid4,editable = False)
    
    def __str__(self):
        return f'Customer {self.user.username}'    
    

class Employee(models.Model):
    """ extra attr unid to display in public space"""
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    location = models.CharField(max_length=250,default='') 
    unid = models.UUIDField(max_length=255, default = uuid.uuid4,editable = False)
    
    def __str__(self):
        return f"Employee {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from .models import Customer,Employee

User = get_user_model()


class CustomerCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('username','email','password1','password2','is_customer') 

    # let op:
    # user.is_customer in forms already (not in view) 
    # @transaction.atomic
    # def save(self,commit=False):
    #     user = super().save(commit=False)
    #     user.is_customer = True
    #     user.save()
    #     customer = Customer.objects.create(user=user)
    #     customer.save()
    #     return user    

class  CustomerChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','avatar','phone_number')
        fields = UserChangeForm.Meta.fields
    
    # @transaction.atomic
    # def save(self):
    #     user = super().save(commit=False)
    #     if self.cleaned_data.get('avatar') is not None:
    #         user.phone_number=self.cleaned_data.get('avatar') 
    #     if self.cleaned_data.get('phone_number') is not None:
    #         user.phone_number=self.cleaned_data.get('phone_number')        
    #     user.save()
    #     customer = Customer.objects.create(user=user)
    #     customer.save()
    #     return user

class EmployeeCreationForm(UserCreationForm):   
    class Meta(UserCreationForm.Meta):
        fields = ('username','email','password1','password2') 
        model = User
    # let op:
    # user.is_employee in forms already (not in view) 
    # @transaction.atomic
    # def save(self,commit=False):
    #     user = super().save(commit=False)
    #     user.is_employee = True
    #     user.save()
    #     employee = Employee.objects.create(user=user)
    #     employee.save()
    #     return user 
    


class  EmployeeChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','avatar','phone_number')
        fields = UserChangeForm.Meta.fields
    
    
    # @transaction.atomic
    # def save(self,commit=False):
    #     user = super().save(commit=False)
    #     if self.cleaned_data.get('avatar') is not None:
    #         user.phone_number=self.cleaned_data.get('avatar') 
    #     if self.cleaned_data.get('phone_number') is not None:
    #         user.phone_number=self.cleaned_data.get('phone_number')        
    #     user.save()
    #     customer = Customer.objects.create(user=user)
    #     customer.save()
    #     return user        

users/views.py
from django.views.generic import CreateView
from django.contrib.auth import get_user_model

User = get_user_model()

from django.contrib.auth.forms import UserCreationForm
from .forms import *

class CustReg(CreateView):
    model = User
    form_class= CustomerCreationForm
    template_name = 'users/cust_registration.html'
    success_url = '/'
   

templates/_extra/nav-bar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>      
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dashboard
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Update Profile</a>
        </li>
      
      <li class="nav-item">
        <a class="nav-link" href="#">LogOut</a>
      </li>
      
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="#">SignUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Log In</a>
      </li>
      {% endif %}
    </ul> 
        
      
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- let op: use here staic/bootstrap folder -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body>
    {% include '_extra/nav-bar.html' %}
    <div>
        {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
       {% endif %}         
    </div>
    {% block content %}
        <div class="container">

        </div>
    {% endblock %}
     <!-- Compiled and minified JavaScript -->
   <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js">
   </script>
   <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- for cookies -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script> 
    <script src="{% static 'js/script.js' %}"></script>
    {% block js %}

    {% endblock %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="jumbotron">
    <h1>Welcome to Our Club </h1>
    <div class="row">
        <div class="col col-md-10">
            {% if user.is_authenticated %}
            <h1>{{user}}</h1>
            {% else %}
            <h1>Welcome,{{user}}</h1>
            {% endif %}
        </div>
    </div>    

</div>
<div class="row">
    <div class="col col-md-6"><button class="btn btn-success"><a href="{% url 'users:customer-signup' %}">Go as a customer</a></button></div>
    <div class="col col-md-6"><a href="{% url 'users:employee-signup' %}">Go as an employee</a></div>
</div>
{% endblock content %}

templates/tut_registration.html
<!-- tutorial about uploading avatar via api rest -->
<!-- заметь: на 1 стр 2 формы,к separ submited (inconvinient) -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p class="text-muted my-3"><small>Open Developer Console for information about responses.</small></p>
                <h1 class="my-3">1. Log in</h1>
                <form id="login_form">
                    <div class="form-group">
                        <label for="id_email">Email address</label>
                        <input type="email" class="form-control" id="id_email" aria-describedby="emailHelp"
                               placeholder="Enter email"/>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" class="form-control" id="id_password" placeholder="Password"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Log in</button>
                </form>
    
                <h1 class="my-3">2. Upload an avatar</h1>
                <form id="avatar_form">
                    <div class="form-group">
                        <label for="id_avatar">Choose an image for your avatar</label>
                        <input type="file" class="form-control-file" id="id_avatar"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
    
            </div>
        </div>
    </div>
    <script src="{% static 'site/js/avatar.js' %}"></script>
    
</body>
</html>

{% for field in form.visible_fields %}
                       <div class="form-group">
                           {{ field.label_tag }}
                              {% render_field field class="form-control" %}
                                {% for error in field.errors %}
                                  <span style="color:red">{{ error }}</span>
                                {% endfor %}
                     {% endfor %}

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
           <section>
            <div class="container">
                <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                    <div class="card-header text-black">
                        <h2>Demo Registration</h2>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                            <a type="button" class="btn btn-block" href="{% url 'customer_register' %}">I am a customer</a>
                            </div>
                            <div class="col-lg-6">
                            <a type="button" class="btn btn-block" href="{% url 'employee_register' %}">I am an employee</a>
                            </div>
                        </div>
                        </form>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </section>
    </div>        
</body>
</html>

templates/users/cust_registration.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<section>
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header text-black">
              <h2>Register</h2>
            </div>
            <div class="card-body">
                <form class="my-form" action="{% url 'users:customer-signup' %}" method="POST" novalidate>
                  {% csrf_token %}
                  {% for field in form.visible_fields %}
                       <div class="form-group">
                           {{ field.label_tag }}
                              {% render_field field class="form-control" %}
                                {% for error in field.errors %}
                                  <span style="color:red">{{ error }}</span>
                                {% endfor %}
                     {% endfor %}
                  {% if form.errors %}
                  <ul>
                    {% for err in form.errors %}
                    <li>{{err}}</li>
                    {% endfor %}
                  </ul>
                  {% endif %}   
                    <input type="submit" value="Register" class="btn btn-block btn-primary">
                    </div>
                </form>
             </div>
                </div>   
            </div>
          </div>
        </div>
    </div>
  </section>
  {% endblock %}

templates/users/empl_registration.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<section>
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header text-black">
              <h2>Register as an employee</h2>
            </div>
            <div class="card-body">
                <form action="{% url 'users:employee-signup' %}" method="POST" novalidate>
                  {% csrf_token %}
                  <!-- Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. -->
                     {% for field in form.visible_fields %}
                       <div class="form-group">
                           {{ field.label_tag }}
                              {% render_field field class="form-control" %}
                                {% for error in field.errors %}
                                  <span style="color:red">{{ error }}</span>
                                {% endfor %}
                     {% endfor %}
                    <input type="submit" value="Register as employee" class="btn btn-block btn-primary">
                    </div>
                </form>
             </div>
                </div>   
            </div>
          </div>
        </div>
    </div>
  </sectio>
  {% endblock %}